"""select_tool.py — Dump / pack Animal Crossing select_data.bin + select_data_table.bin.

The select_data files store the player-choice strings ("Never mind...",
"Mail a letter", "Yes!", etc.) as a flat byte array with an offset table.

Table format
------------
select_data_table.bin: N big-endian uint32 values.
    table[i] = byte offset in select_data.bin where entry i+1 begins.
    Entry 0 always starts at byte 0 of the data file.
    Entry i occupies bytes [table[i-1] .. table[i])   (or [0 .. table[0]) for i=0).
    Entries whose computed size is 0 are treated as empty (placeholder).

Valid range: 0 .. mChoice_SELECT_STR_NUM-1  (= 0 .. 606, inclusive).
The table file contains 750 entries total; entries 607-749 are zero-padding.

Character encoding
------------------
Same single-byte AC charset used by message_data.bin (see CHAR_MAP in msg_tool.py).
ASCII range 0x20-0x7E maps as expected.  Accented / special chars use the
extended table (e.g. 'à'=0xe0, 'é'=0xe9, 'ì'=0xec, 'ñ'=0xf1, 'ü'=0xfc).

Text file format
----------------
  Lines starting with # are comments (ignored on pack).
  Each entry is introduced by [[ENTRY N]] on its own line.
  The translation string follows on the NEXT NON-BLANK, NON-COMMENT line.
  Empty [[ENTRY N]] blocks (no text before the next [[ENTRY]] marker) produce
  empty strings (the game fills with spaces at runtime).
  Only entries 0..606 are read/written; the table is zero-padded to 750 slots.

Usage
-----
  python -m tools.select_tool dump  select_data.bin select_data_table.bin out.txt
  python -m tools.select_tool pack  in.txt  select_data.bin select_data_table.bin
         [--data-size HEX] [--table-size HEX]
"""

import argparse
import struct
import sys
from pathlib import Path

# Import the AC charset from msg_tool so we stay in sync with the rest of the pipeline.
_TOOLS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(_TOOLS_DIR))
from msg_tool import CHAR_MAP  # noqa: E402 (import after path setup)

# Reverse map: unicode character → AC byte value
_CHAR_TO_BYTE: dict[str, int] = {}
for _i, _ch in enumerate(CHAR_MAP):
    if _ch not in _CHAR_TO_BYTE:
        _CHAR_TO_BYTE[_ch] = _i

VALID_COUNT = 607        # mChoice_SELECT_STR_NUM  (entries 0-606 are valid)
TABLE_TOTAL = 750        # total slots in select_data_table.bin
DATA_PAD    = 0x1B58     # padded size of select_data.bin  (original USA)
TABLE_PAD   = TABLE_TOTAL * 4  # = 0x0BB8


# ── Character encoding helpers ────────────────────────────────────────────────

def decode_ac_bytes(raw: bytes) -> str:
    """Decode AC-charset bytes to a Unicode string."""
    return "".join(CHAR_MAP[b] for b in raw)


def encode_ac_str(text: str) -> bytes:
    """Encode a Unicode string to AC-charset bytes.

    Raises ValueError if a character has no AC mapping.
    """
    out = bytearray()
    for ch in text:
        if ch not in _CHAR_TO_BYTE:
            raise ValueError(
                f"Character {ch!r} (U+{ord(ch):04X}) has no AC charset mapping"
            )
        out.append(_CHAR_TO_BYTE[ch])
    return bytes(out)


# ── Binary parsing ────────────────────────────────────────────────────────────

def parse_select(data_bytes: bytes, table_bytes: bytes) -> list[bytes]:
    """Return a list of VALID_COUNT byte strings (may be empty)."""
    n = len(table_bytes) // 4
    table = [struct.unpack_from(">I", table_bytes, i * 4)[0] for i in range(n)]

    result: list[bytes] = []
    for i in range(VALID_COUNT):
        end = table[i] if i < n else len(data_bytes)
        start = table[i - 1] if i > 0 else 0
        if end == 0 or end < start:
            result.append(b"")
        else:
            result.append(data_bytes[start:end])
    return result


# ── Dump ─────────────────────────────────────────────────────────────────────

def dump(data_path: str, table_path: str, out_path: str) -> None:
    data_bytes  = Path(data_path).read_bytes()
    table_bytes = Path(table_path).read_bytes()
    strings = parse_select(data_bytes, table_bytes)

    lines = [
        "# Animal Crossing — select string translation file",
        "# Generated by tools/select_tool.py",
        "#",
        "# Instructions:",
        "#   Translate the line after each [[ENTRY N]] marker.",
        "#   Leave the entry blank if you want the game to show spaces.",
        "#   Max display length is 16 characters (longer strings are clipped).",
        "#   Use the AC charset: standard ASCII plus accented chars",
        "#   (à é è ì ò ù â ê î ô û ä ë ï ö ü ñ ç ß Ä Ö Ü etc.).",
        "#   Do NOT modify the [[ENTRY N]] markers or comment lines.",
        "#   Control codes (<<...>>) are NOT supported in select strings.",
        "",
    ]

    for i, raw in enumerate(strings):
        lines.append(f"[[ENTRY {i}]]")
        if raw:
            lines.append(decode_ac_bytes(raw))
        # blank line follows to visually separate entries
        lines.append("")

    Path(out_path).write_text("\n".join(lines), encoding="utf-8")
    non_empty = sum(1 for r in strings if r)
    print(f"Dumped {non_empty} non-empty entries (of {VALID_COUNT}) → {out_path}")


# ── Pack ─────────────────────────────────────────────────────────────────────

def pack(
    in_path: str,
    data_path: str,
    table_path: str,
    data_size: int = DATA_PAD,
    table_size: int = TABLE_PAD,
) -> None:
    text = Path(in_path).read_text(encoding="utf-8")

    # Parse: collect {index → unicode string}
    entries: dict[int, str] = {}
    current_idx: int | None = None

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[[ENTRY ") and line.endswith("]]"):
            try:
                current_idx = int(line[8:-2])
                entries.setdefault(current_idx, "")
            except ValueError:
                pass
            continue
        if current_idx is not None and entries.get(current_idx, "") == "":
            # First non-blank, non-comment line after the marker is the string.
            entries[current_idx] = line

    # Build binary data and table
    data_out  = bytearray()
    table_out = bytearray(table_size)  # zero-filled

    errors = []
    for i in range(VALID_COUNT):
        text_str = entries.get(i, "")
        if text_str:
            try:
                encoded = encode_ac_str(text_str)
            except ValueError as e:
                errors.append(f"  entry {i}: {e}")
                encoded = b""
        else:
            encoded = b""
        data_out.extend(encoded)
        struct.pack_into(">I", table_out, i * 4, len(data_out))
    # entries VALID_COUNT..TABLE_TOTAL-1 remain 0 (already zeroed)

    if errors:
        print("Encoding errors (entries skipped):")
        for msg in errors:
            print(msg)

    # Pad data to original size
    if len(data_out) < data_size:
        data_out.extend(b"\x00" * (data_size - len(data_out)))

    Path(data_path).write_bytes(bytes(data_out))
    Path(table_path).write_bytes(bytes(table_out))
    non_empty = sum(1 for i in range(VALID_COUNT) if entries.get(i, ""))
    print(f"Packed {non_empty} non-empty entries (of {VALID_COUNT})")
    print(f"  → {data_path}")
    print(f"  → {table_path}")


# ── CLI ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Dump / pack select_data.bin for the Animal Crossing PC port.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    sub = parser.add_subparsers(dest="command", required=True)

    d = sub.add_parser("dump", help="Dump select_data.bin → translatable text file")
    d.add_argument("data",  help="Input select_data.bin")
    d.add_argument("table", help="Input select_data_table.bin")
    d.add_argument("out",   help="Output text file")

    p = sub.add_parser("pack", help="Pack translated text → select_data.bin")
    p.add_argument("text",  help="Input text file (produced by dump / hand-edited)")
    p.add_argument("data",  help="Output select_data.bin")
    p.add_argument("table", help="Output select_data_table.bin")
    p.add_argument(
        "--data-size",
        default=hex(DATA_PAD),
        help=f"Padded data binary size in hex (default {hex(DATA_PAD)})",
    )
    p.add_argument(
        "--table-size",
        default=hex(TABLE_PAD),
        help=f"Padded table binary size in hex (default {hex(TABLE_PAD)})",
    )

    args = parser.parse_args()

    if args.command == "dump":
        dump(args.data, args.table, args.out)
    else:
        data_sz  = int(args.data_size,  16)
        table_sz = int(args.table_size, 16)
        pack(args.text, args.data, args.table, data_sz, table_sz)


if __name__ == "__main__":
    main()
